"""Training script for texture inpainting model (Model 5 — texture).

Trains a U-Net to fill unobserved UV texture regions from partial textures
generated by multi-view projection.  Loss: L1 reconstruction + optional
perceptual (VGG).  Evaluation metrics: L1, SSIM.

Supports mixed precision (fp16) on CUDA, TensorBoard visual logging, and
checkpoint resume.

Usage::

    python -m training.train_texture_inpainting --config training/configs/texture_inpainting.yaml

Pure Python + PyTorch (no Blender dependency).
"""

from __future__ import annotations

import argparse
import logging
import math
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F
import yaml

from training.data.texture_inpainting_dataset import (
    TextureInpaintingDataset,
    TextureInpaintingDatasetConfig,
)
from training.models.texture_inpainting_model import TextureInpaintingModel
from training.utils.checkpoint import EarlyStopping, save_checkpoint

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Perceptual loss (VGG feature matching)
# ---------------------------------------------------------------------------


class PerceptualLoss(nn.Module):
    """VGG16 feature-matching loss for perceptual quality."""

    def __init__(self, device: torch.device) -> None:
        super().__init__()
        from torchvision.models import vgg16

        vgg = vgg16(weights="IMAGENET1K_V1").features[:16].to(device)
        vgg.eval()
        for p in vgg.parameters():
            p.requires_grad = False
        self.vgg = vgg

        # ImageNet normalization
        self.register_buffer("mean", torch.tensor([0.485, 0.456, 0.406]).view(1, 3, 1, 1))
        self.register_buffer("std", torch.tensor([0.229, 0.224, 0.225]).view(1, 3, 1, 1))

    def _normalize(self, x: torch.Tensor) -> torch.Tensor:
        """Normalize RGB channels (drop alpha)."""
        rgb = x[:, :3]
        return (rgb - self.mean) / self.std

    def forward(self, pred: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
        pred_f = self.vgg(self._normalize(pred))
        target_f = self.vgg(self._normalize(target))
        return F.l1_loss(pred_f, target_f)


# ---------------------------------------------------------------------------
# SSIM metric
# ---------------------------------------------------------------------------


def _ssim(
    pred: torch.Tensor,
    target: torch.Tensor,
    window_size: int = 11,
    c1: float = 0.01**2,
    c2: float = 0.03**2,
) -> torch.Tensor:
    """Compute mean SSIM between pred and target (RGB channels only).

    Args:
        pred: ``[B, C, H, W]`` predicted RGBA in [0, 1].
        target: ``[B, C, H, W]`` ground truth RGBA in [0, 1].

    Returns:
        Scalar mean SSIM value.
    """
    # Use RGB only
    x = pred[:, :3]
    y = target[:, :3]

    # Gaussian window
    channels = 3
    kernel_1d = torch.arange(window_size, dtype=torch.float32, device=x.device)
    kernel_1d = kernel_1d - window_size // 2
    kernel_1d = torch.exp(-0.5 * (kernel_1d / 1.5) ** 2)
    kernel_1d = kernel_1d / kernel_1d.sum()
    kernel_2d = kernel_1d[:, None] * kernel_1d[None, :]
    window = kernel_2d.expand(channels, 1, window_size, window_size).contiguous()

    pad = window_size // 2
    mu_x = F.conv2d(x, window, padding=pad, groups=channels)
    mu_y = F.conv2d(y, window, padding=pad, groups=channels)

    mu_x_sq = mu_x * mu_x
    mu_y_sq = mu_y * mu_y
    mu_xy = mu_x * mu_y

    sigma_x_sq = F.conv2d(x * x, window, padding=pad, groups=channels) - mu_x_sq
    sigma_y_sq = F.conv2d(y * y, window, padding=pad, groups=channels) - mu_y_sq
    sigma_xy = F.conv2d(x * y, window, padding=pad, groups=channels) - mu_xy

    ssim_map = ((2 * mu_xy + c1) * (2 * sigma_xy + c2)) / (
        (mu_x_sq + mu_y_sq + c1) * (sigma_x_sq + sigma_y_sq + c2)
    )
    return ssim_map.mean()


# ---------------------------------------------------------------------------
# LR schedule
# ---------------------------------------------------------------------------


def _adjust_lr(
    optimizer: torch.optim.Optimizer,
    epoch: int,
    total_epochs: int,
    warmup_epochs: int,
    base_lr: float,
) -> float:
    """Linear warmup + cosine annealing schedule."""
    if epoch < warmup_epochs:
        lr = base_lr * (epoch + 1) / warmup_epochs
    else:
        progress = (epoch - warmup_epochs) / max(total_epochs - warmup_epochs, 1)
        lr = base_lr * 0.5 * (1.0 + math.cos(math.pi * progress))

    for pg in optimizer.param_groups:
        pg["lr"] = lr
    return lr


# ---------------------------------------------------------------------------
# Train / validate
# ---------------------------------------------------------------------------


def train_one_epoch(
    model: TextureInpaintingModel,
    loader: torch.utils.data.DataLoader,
    optimizer: torch.optim.Optimizer,
    device: torch.device,
    l1_weight: float,
    perceptual_loss: PerceptualLoss | None,
    perceptual_weight: float,
    scaler: torch.amp.GradScaler | None,
) -> dict[str, float]:
    """Train for one epoch. Returns average losses."""
    model.train()
    total_l1 = 0.0
    total_perc = 0.0
    total_loss = 0.0
    n_batches = 0
    use_amp = scaler is not None

    for batch in loader:
        image = batch["image"].to(device)
        target = batch["target"].to(device)

        with torch.amp.autocast("cuda", enabled=use_amp):
            outputs = model(image)
            pred = outputs["inpainted"]

            # L1 loss
            l1 = F.l1_loss(pred, target)
            loss = l1_weight * l1

            # Perceptual loss
            perc_val = 0.0
            if perceptual_loss is not None and perceptual_weight > 0:
                perc = perceptual_loss(pred, target)
                loss = loss + perceptual_weight * perc
                perc_val = perc.item()

        optimizer.zero_grad()
        if scaler is not None:
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
        else:
            loss.backward()
            optimizer.step()

        total_l1 += l1.item()
        total_perc += perc_val
        total_loss += loss.item()
        n_batches += 1

    d = max(n_batches, 1)
    return {
        "train/loss": total_loss / d,
        "train/l1": total_l1 / d,
        "train/perceptual": total_perc / d,
    }


@torch.no_grad()
def validate(
    model: TextureInpaintingModel,
    loader: torch.utils.data.DataLoader,
    device: torch.device,
    l1_weight: float,
    perceptual_loss: PerceptualLoss | None,
    perceptual_weight: float,
) -> dict[str, float]:
    """Validate. Returns average losses + SSIM."""
    model.eval()
    total_l1 = 0.0
    total_perc = 0.0
    total_loss = 0.0
    total_ssim = 0.0
    n_batches = 0

    for batch in loader:
        image = batch["image"].to(device)
        target = batch["target"].to(device)

        outputs = model(image)
        pred = outputs["inpainted"]

        l1 = F.l1_loss(pred, target)
        loss = l1_weight * l1

        perc_val = 0.0
        if perceptual_loss is not None and perceptual_weight > 0:
            perc = perceptual_loss(pred, target)
            loss = loss + perceptual_weight * perc
            perc_val = perc.item()

        ssim_val = _ssim(pred, target).item()

        total_l1 += l1.item()
        total_perc += perc_val
        total_loss += loss.item()
        total_ssim += ssim_val
        n_batches += 1

    d = max(n_batches, 1)
    return {
        "val/loss": total_loss / d,
        "val/l1": total_l1 / d,
        "val/perceptual": total_perc / d,
        "val/ssim": total_ssim / d,
    }


# ---------------------------------------------------------------------------
# TensorBoard visual logging
# ---------------------------------------------------------------------------


def _log_visual_comparison(
    writer: object,
    model: TextureInpaintingModel,
    val_loader: torch.utils.data.DataLoader,
    device: torch.device,
    epoch: int,
    max_images: int = 4,
) -> None:
    """Log partial | predicted | GT comparison to TensorBoard."""
    model.eval()
    batch = next(iter(val_loader))
    image = batch["image"][:max_images].to(device)
    target = batch["target"][:max_images]

    with torch.no_grad():
        pred = model(image)["inpainted"].cpu()

    partial_rgb = image[:, :3].cpu()  # [N, 3, H, W]
    target_rgb = target[:, :3]  # [N, 3, H, W]

    # Build comparison grid: partial | predicted | GT
    grid_rows = []
    for i in range(pred.shape[0]):
        row = torch.cat([partial_rgb[i], pred[i, :3], target_rgb[i]], dim=2)
        grid_rows.append(row)

    grid = torch.cat(grid_rows, dim=1)  # [3, N*H, 3*W]
    writer.add_image("val/comparison", grid.clamp(0, 1), epoch)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Train texture inpainting model (Model 5 — texture)"
    )
    parser.add_argument("--config", type=Path, required=True, help="YAML config path")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(name)s %(levelname)s %(message)s",
    )

    cfg = yaml.safe_load(args.config.read_text(encoding="utf-8"))
    train_cfg = cfg.get("training", {})
    loss_cfg = cfg.get("loss", {})
    ckpt_cfg = cfg.get("checkpointing", {})
    model_cfg = cfg.get("model", {})

    device = torch.device(
        "cuda"
        if torch.cuda.is_available()
        else "mps"
        if hasattr(torch.backends, "mps") and torch.backends.mps.is_available()
        else "cpu"
    )
    logger.info("Using device: %s", device)

    # --- Mixed precision ---
    use_amp = train_cfg.get("mixed_precision", False) and device.type == "cuda"
    scaler = torch.amp.GradScaler("cuda") if use_amp else None
    if use_amp:
        logger.info("Mixed precision (fp16) enabled")

    # --- Dataset ---
    ds_config = TextureInpaintingDatasetConfig.from_dict(cfg)

    train_ds = TextureInpaintingDataset(
        TextureInpaintingDatasetConfig(**{**ds_config.__dict__, "split": "train"})
    )
    val_ds = TextureInpaintingDataset(
        TextureInpaintingDatasetConfig(**{**ds_config.__dict__, "split": "val"})
    )

    train_loader = torch.utils.data.DataLoader(
        train_ds,
        batch_size=train_cfg.get("batch_size", 4),
        shuffle=True,
        num_workers=train_cfg.get("num_workers", 4),
        pin_memory=True,
        drop_last=True,
    )
    val_loader = torch.utils.data.DataLoader(
        val_ds,
        batch_size=train_cfg.get("batch_size", 4),
        shuffle=False,
        num_workers=train_cfg.get("num_workers", 4),
        pin_memory=True,
    )

    # --- Model ---
    model = TextureInpaintingModel(
        in_channels=model_cfg.get("in_channels", 5),
        out_channels=model_cfg.get("out_channels", 4),
    ).to(device)

    param_count = sum(p.numel() for p in model.parameters() if p.requires_grad)
    logger.info("Model parameters: %s", f"{param_count:,}")

    # --- Optimizer ---
    base_lr = train_cfg.get("learning_rate", 2e-4)
    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=base_lr,
        weight_decay=train_cfg.get("weight_decay", 1e-5),
    )

    # --- Loss ---
    l1_weight = loss_cfg.get("l1_weight", 1.0)
    perceptual_weight = loss_cfg.get("perceptual_weight", 0.1)

    perceptual_loss: PerceptualLoss | None = None
    if perceptual_weight > 0:
        try:
            perceptual_loss = PerceptualLoss(device)
            logger.info("Perceptual loss enabled (weight=%.3f)", perceptual_weight)
        except Exception as e:
            logger.warning("Could not load VGG for perceptual loss: %s", e)
            perceptual_loss = None

    # --- Checkpointing ---
    save_dir = Path(ckpt_cfg.get("save_dir", "./checkpoints/texture_inpainting"))
    save_dir.mkdir(parents=True, exist_ok=True)

    es_metric = ckpt_cfg.get("early_stopping_metric", "val/l1")
    es_patience = ckpt_cfg.get("early_stopping_patience", 15)
    early_stopping = EarlyStopping(patience=es_patience, metric_name=es_metric, mode="min")

    # --- TensorBoard ---
    try:
        from torch.utils.tensorboard import SummaryWriter

        tb_writer = SummaryWriter(log_dir=str(save_dir / "tb_logs"))
        logger.info("TensorBoard logging to %s", save_dir / "tb_logs")
    except ImportError:
        tb_writer = None
        logger.warning("TensorBoard not available — skipping visual logging")

    # --- Resume from checkpoint ---
    start_epoch = 0
    best_val_l1 = float("inf")
    resume_path = save_dir / "latest.pt"
    if resume_path.exists():
        from training.utils.checkpoint import load_checkpoint

        info = load_checkpoint(resume_path, model, optimizer)
        start_epoch = info["epoch"] + 1
        logger.info("Resumed from epoch %d", start_epoch)

    # --- Training loop ---
    epochs = train_cfg.get("epochs", 100)
    warmup = train_cfg.get("warmup_epochs", 5)
    log_images_every = 5

    for epoch in range(start_epoch, epochs):
        lr = _adjust_lr(optimizer, epoch, epochs, warmup, base_lr)

        train_metrics = train_one_epoch(
            model,
            train_loader,
            optimizer,
            device,
            l1_weight,
            perceptual_loss,
            perceptual_weight,
            scaler,
        )
        val_metrics = validate(
            model,
            val_loader,
            device,
            l1_weight,
            perceptual_loss,
            perceptual_weight,
        )

        all_metrics = {**train_metrics, **val_metrics, "lr": lr}

        logger.info(
            "Epoch %d/%d — lr=%.2e | train/l1=%.4f | val/l1=%.4f | val/ssim=%.4f",
            epoch + 1,
            epochs,
            lr,
            train_metrics["train/l1"],
            val_metrics["val/l1"],
            val_metrics["val/ssim"],
        )

        # TensorBoard logging
        if tb_writer is not None:
            for key, value in all_metrics.items():
                tb_writer.add_scalar(key, value, epoch)
            if epoch % log_images_every == 0 and len(val_ds) > 0:
                _log_visual_comparison(tb_writer, model, val_loader, device, epoch)

        # Save latest
        save_checkpoint(model, optimizer, None, epoch, all_metrics, save_dir / "latest.pt")

        # Save best
        if val_metrics["val/l1"] < best_val_l1:
            best_val_l1 = val_metrics["val/l1"]
            save_checkpoint(model, optimizer, None, epoch, all_metrics, save_dir / "best.pt")
            logger.info("  New best val/l1: %.4f", best_val_l1)

        # Early stopping
        if early_stopping.step(all_metrics):
            break

    if tb_writer is not None:
        tb_writer.close()

    logger.info("Training complete. Best val/l1: %.4f", best_val_l1)


if __name__ == "__main__":
    main()
