#!/usr/bin/env python3
"""Generate diverse, self-contained character prompts for Gemini/Sora.

Each prompt is fully standalone — specific style, specific character, specific
pose. Format matches the reference prompt with demographic descriptor and all
framing/background specifications.

Usage::

    python3 scripts/generate_character_prompts.py --count 100 --start_id 61
"""

from __future__ import annotations

import argparse
import random
from dataclasses import dataclass
from pathlib import Path


# ---------------------------------------------------------------------------
# Pools
# ---------------------------------------------------------------------------

STYLES = [
    "Full-body watercolor",
    "Full-body oil painting",
    "Full-body gouache illustration",
    "Full-body digital painting",
    "Full-body anime cel-shaded illustration",
    "Full-body manga ink drawing",
    "Full-body flat vector illustration",
    "Full-body retro pixel art",
    "Full-body storybook illustration in gouache",
    "Full-body concept art painting",
    "Full-body pop art illustration",
    "Full-body pastel chalk illustration",
    "Full-body ink and wash illustration",
    "Full-body soft-shaded cartoon",
    "Full-body minimal line art with watercolor wash",
]

STYLE_FINISHES = {
    "Full-body watercolor": "Delicate watercolor.",
    "Full-body oil painting": "Rich oil painting with visible brushwork.",
    "Full-body gouache illustration": "Warm gouache tones.",
    "Full-body digital painting": "Painterly digital art.",
    "Full-body anime cel-shaded illustration": "Clean anime cel shading.",
    "Full-body manga ink drawing": "High-contrast ink lines.",
    "Full-body flat vector illustration": "Bold flat colors with minimal shading.",
    "Full-body retro pixel art": "Crisp retro pixel art.",
    "Full-body storybook illustration in gouache": "Cozy children's book style.",
    "Full-body concept art painting": "Detailed concept art.",
    "Full-body pop art illustration": "Bold pop art with graphic shapes.",
    "Full-body pastel chalk illustration": "Soft pastel chalk textures.",
    "Full-body ink and wash illustration": "Traditional ink and wash.",
    "Full-body soft-shaded cartoon": "Smooth cartoon shading.",
    "Full-body minimal line art with watercolor wash": "Clean linework with soft color wash.",
}

POSES = [
    ("standing in a neutral rest pose", "neutral"),
    ("standing in an A-pose with arms slightly out and legs apart", "a_pose"),
    ("standing in a T-pose with arms fully extended horizontally", "t_pose"),
    ("walking with one foot forward in a confident stride", "walking"),
    ("mid-swing of a powerful action pose", "action"),
    ("crouched low with one hand on the ground", "crouch"),
    ("sitting on the floor with legs crossed", "sitting"),
    ("standing with hands on hips in a heroic pose", "hands_on_hips"),
    ("standing with one arm raised overhead", "arm_raised"),
    ("leaning slightly forward in an expressive gesture", "leaning"),
    ("holding an object close to the chest with both hands", "holding_chest"),
    ("stepping forward in an enthusiastic stance", "stepping"),
    ("mid-run with arms pumping", "running"),
    ("mid-jump with both feet off the ground", "jumping"),
    ("kneeling on one knee in a reverent pose", "kneeling"),
    ("standing side-profile with arms crossed", "arms_crossed"),
    ("dancing with one leg lifted and arms flowing", "dancing"),
    ("reaching forward with one outstretched hand", "reaching"),
]

# (character description, demographic descriptor)
# description = visible outfit + props; demographic = gender/ethnicity/feel
CHARACTERS = [
    ("a teenage girl in a sailor school uniform — pleated skirt, navy top with white collar, ribbon tie, knee socks, loafers, and a schoolbag slung over one shoulder",
     "feminine-presenting, cheerful, with East Asian features"),
    ("an elderly wizard with a long white beard, dark blue robe embroidered with silver moons, a tall pointed hat, leather sandals, and a twisted wooden staff",
     "masculine-presenting, wise, with pale European features"),
    ("a muscular barbarian warrior in a fur loincloth, leather boots, wrist bracers, with tribal tattoos, and wielding a massive double-bladed axe",
     "masculine-presenting, fierce, with bronzed Nordic features"),
    ("a bicycle delivery rider in a branded windbreaker, cap, cargo shorts, sneakers, a backpack, and holding a pizza box",
     "non-binary-presenting, energetic, with South Asian features"),
    ("a noir detective in a long trench coat, fedora, dress shirt, slacks, leather shoes, and a cigarette held loosely",
     "masculine-presenting, brooding, with Mediterranean features"),
    ("a tiny hedgehog knight standing upright in handmade tin-plate armor, tiny gauntlets, a twig sword, and a leaf cape",
     "androgynous creature character, plucky and small"),
    ("a space marine in bulky power armor with shoulder pauldrons, full-face helmet, a plasma rifle slung across the chest, and heavy armored boots",
     "masculine-presenting, imposing, visible armor only"),
    ("a high school baseball player in a white jersey, striped pants, cleats, batting gloves, helmet, and gripping a wooden bat",
     "masculine-presenting, athletic, with East Asian features"),
    ("a 1960s pop singer in a bright mod mini-dress, white go-go boots, big hoop earrings, a beehive hairdo, and a microphone in one hand",
     "feminine-presenting, vibrant, with Black features"),
    ("a yoga instructor in fitted leggings, a tank top, bare feet, a beaded bracelet, and a rolled mat under one arm",
     "feminine-presenting, serene, with South American features"),
    ("a dark elf ranger in dark leather armor, a hooded cloak, twin curved daggers, tall boots, and long silver-white hair",
     "androgynous, mysterious, with pointed ears and deep purple skin"),
    ("a chubby baker in a white apron over a checkered shirt, a chef's hat, rolled sleeves, wooden clogs, and a tray of pastries",
     "masculine-presenting, friendly, with Northern European features"),
    ("a Renaissance courtier in a velvet doublet, puffed hose, a ruff collar, a feathered cap, pointed shoes, and a rapier at the hip",
     "masculine-presenting, refined, with pale European features"),
    ("a magical girl in a frilly pink dress with layered skirts, thigh-high white boots, puff sleeves, twin ponytails, and wielding a star-tipped wand",
     "feminine-presenting, sparkling, with fair skin and large anime eyes"),
    ("a hiker in cargo shorts, trail boots, a flannel shirt tied at the waist, a sun hat, and carrying a heavy backpack",
     "masculine-presenting, rugged, with Latin features"),
    ("a steampunk inventor in a brass-buckled corset, a leather utility skirt, knee-high laced boots, goggles pushed up on the forehead, and carrying a wrench",
     "feminine-presenting, inventive, with ginger hair and freckled pale skin"),
    ("a skateboarder teen in baggy jeans, an oversized graphic t-shirt, high-top sneakers, a backwards cap, and wrist guards",
     "masculine-presenting, laid-back, with mixed-race features"),
    ("a gardener grandmother in a floral apron, a wide-brimmed straw hat, rubber clogs, garden gloves, and carrying a watering can",
     "feminine-presenting, kind, with Southeast Asian features"),
    ("a ballet dancer in a white tutu, pink pointe shoes, a tight bun, and wrist ribbons, with defined dancer's posture",
     "feminine-presenting, graceful, with Eastern European features"),
    ("a small dragon boy with green scales, tiny wings, a lizard tail, wearing a simple brown tunic, rope belt, and barefoot",
     "androgynous young creature character, curious and bright"),
    ("an 8-bit-style plumber in blue denim overalls, a red cap, white gloves, brown work boots, and a mustache",
     "masculine-presenting, plucky, with Italian features"),
    ("a samurai in a full kimono and hakama, two katanas at the belt, straw sandals, a topknot hairstyle, and a stern expression",
     "masculine-presenting, disciplined, with Japanese features"),
    ("a 1970s disco dancer in flared bell-bottoms, a rhinestone vest, platform shoes, layered gold chains, and an impressive afro",
     "masculine-presenting, charismatic, with Black features"),
    ("a programmer in a hoodie, skinny jeans, low sneakers, wireless headphones around the neck, and holding a slim laptop",
     "non-binary-presenting, focused, with Middle Eastern features"),
    ("a desert cowboy in a long duster coat, a wide-brimmed hat, a neck bandana, leather gloves, cowboy boots with spurs, and a revolver holstered",
     "masculine-presenting, weathered, with Mexican features"),
    ("a cat character standing upright on hind legs in a chef's hat and apron, a wooden spatula in one paw, and a mischievous grin",
     "androgynous cat character, cheerful cartoon"),
    ("a Victorian governess in a long dark dress with a high collar, a small hat, button-up boots, carrying a book",
     "feminine-presenting, stern, with English features"),
    ("a cyber-ninja in a sleek black bodysuit with glowing neon accents, a mask covering the lower face, wrist gauntlets, and a katana drawn",
     "androgynous, sleek, with mirrored visor hiding the eyes"),
    ("a mermaid princess with an iridescent fish tail, a shell bikini top, a pearl necklace, flowing long hair, and seaweed hair ornaments",
     "feminine-presenting, ethereal, with Polynesian features"),
    ("a fantasy paladin in ornate gold-trimmed plate armor over a tabard, steel greaves, a massive two-handed sword held vertical, and a shield slung on the back",
     "masculine-presenting, noble, with Norse features"),
    ("a cozy winter character in a long puffer coat, a chunky knit scarf, a wool beanie, snow boots, mittens, and holding a steaming coffee cup",
     "feminine-presenting, cozy, with Scandinavian features"),
    ("a farmer in denim overalls over a plaid shirt, work boots, a straw hat, rolled sleeves, and carrying a pitchfork",
     "masculine-presenting, hardy, with Appalachian features"),
    ("a circus clown in big red shoes, striped baggy pants, colorful suspenders, a polka-dot bow tie, red nose, and a curly rainbow wig",
     "androgynous, whimsical, with white face paint"),
    ("a tiny mouse character standing upright in a little dress and apron, tiny leather shoes, whiskers, and carrying a basket of berries",
     "androgynous mouse character, gentle and small"),
    ("a medieval archer in a forest-green tunic, brown leggings, leather boots, a quiver of arrows across the back, and holding a longbow",
     "feminine-presenting, agile, with Celtic features"),
    ("a track sprinter in a bright singlet and shorts, sleek running shoes, numbered bib, and defined runner's build",
     "masculine-presenting, fast, with Kenyan features"),
    ("a 1950s diner waitress in a pink uniform dress, white apron, a small cap, roller skates, and balancing a tray of milkshakes",
     "feminine-presenting, friendly, with pale American features"),
    ("a tall fashion model in a long tailored coat, wide-leg trousers, sharp heeled boots, designer sunglasses, and a sleek bob haircut",
     "feminine-presenting, poised, with West African features"),
    ("a frost mage in layered robes with fur trim, a crystal-tipped staff, leather boots, long braided hair, and ice crystals forming around the hands",
     "feminine-presenting, cold and regal, with Inuit features"),
    ("a chibi astronaut in a puffy white space suit, helmet visor raised, bulky gloves, moon boots, and a small oxygen pack",
     "androgynous small chibi character, curious"),
    ("a pirate captain in a tricorn hat, a long gold-trimmed coat, a white ruffled shirt, a cutlass sheathed at the belt, and knee-high boots",
     "masculine-presenting, roguish, with Caribbean features"),
    ("a battle robot girl with chrome-plated mecha limbs showing joint lines, a human-looking face, short combat skirt, and glowing joint lights",
     "feminine-presenting mecha character, visible hybrid body"),
    ("a ghost child in a long white nightgown, bare feet not quite touching the ground, translucent pale skin, holding a teddy bear",
     "androgynous, melancholic, with translucent form"),
    ("a desert post-apocalyptic raider in layered sand-colored robes, a gas mask, dust goggles, heavy combat boots, and a slung rifle",
     "masculine-presenting, grim, features mostly hidden by mask"),
    ("a blacksmith apprentice in a heavy leather apron over a simple shirt, thick elbow-length gloves, work boots, rolled sleeves, and holding a glowing horseshoe with tongs",
     "masculine-presenting, strong, with Mediterranean features"),
    ("a circus acrobat in a sparkly sequined leotard, soft ballet slippers, wrist ribbons, a tiara, and striking a balletic pose",
     "feminine-presenting, lithe, with Russian features"),
    ("a wise tortoise elder standing upright in a knitted wool vest, a monocle, holding a walking stick with a gnarled grip",
     "androgynous reptile character, scholarly"),
    ("a cyberpunk netrunner in a long black coat with LED lining, a visor over the eyes, combat boots, fingerless gloves, and holding a data-slate",
     "androgynous, sleek, with partially shaved head"),
    ("an ice skater in a sparkling pale-blue costume, white figure skates, delicate tights, sequins catching the light, and arms in graceful sweep",
     "feminine-presenting, elegant, with pale Slavic features"),
    ("a superhero in a bright primary-red-and-blue costume, a flowing cape, domino mask, knee-high boots, and gold belt buckle",
     "masculine-presenting, heroic, with classic comic-book features"),
    ("a yoga practitioner in loose linen pants and a cropped top, barefoot with a mala bracelet, serene expression, and toned arms",
     "feminine-presenting, serene, with Indian features"),
    ("a swamp witch in a layered patchwork cloak of mossy fabrics, tangled gray hair with small bones, bare dirty feet, and a gnarled staff",
     "feminine-presenting, eerie, with pale warty skin"),
    ("a penguin butler standing upright in a tiny tailored tuxedo, a bow tie, white gloves, and balancing a silver serving tray",
     "androgynous penguin character, dignified"),
    ("a Regency-era gentleman in a high-collared tailcoat, a crisp cravat, high-waisted trousers, riding boots, and a cane held in one hand",
     "masculine-presenting, elegant, with English features"),
    ("a shrine maiden in a white kimono-style haori top, bright red hakama pants, wooden geta sandals, holding a paper ofuda charm",
     "feminine-presenting, calm, with Japanese features"),
    ("a forest druid in green moss-woven robes, a crown of branching antlers, bare feet wrapped in vines, holding a small glowing seed",
     "androgynous, ancient, with olive skin and leaf-markings"),
    ("a space bounty hunter in segmented armor plates over a dark bodysuit, a helmet with a glowing orange visor, knee-high boots, and a plasma rifle",
     "gender-ambiguous due to full armor, imposing"),
    ("a national park ranger in a beige uniform shirt with patches, olive-green pants, a wide belt, hiking boots, and a wide-brim ranger hat",
     "masculine-presenting, friendly, with Native American features"),
    ("a lighthouse keeper in a thick wool sweater, waterproof overalls, tall rubber boots, a weathered captain's cap, and holding a lantern",
     "masculine-presenting, weathered, with Irish features"),
    ("a Thai Muay Thai fighter in traditional rope-wrapped shorts, hand wraps, a mongkhon headband, bare feet, and a muscular defined build",
     "masculine-presenting, focused, with Thai features"),
    ("a mushroom witch with a large red-and-white-speckled mushroom cap as a hat, a dress of overlapping fungi, bare gnarled feet, and spores floating around",
     "feminine-presenting, whimsical, with pale forest skin"),
    ("a Mongolian eagle hunter in a long embroidered chapan coat with fur trim, thick felt boots, a fox-fur hat, and a leather gauntlet with a golden eagle perched",
     "masculine-presenting, stoic, with Mongolian features"),
    ("a fire ant soldier standing upright with a segmented glossy red insect body, mandibles, six limbs (two as arms, four as legs), and tiny armor plates",
     "insectoid creature character, alien and martial"),
    ("a librarian ghost floating slightly above the ground in a long Victorian dress, translucent body, spectral book chains around the arms, and glowing eyes",
     "feminine-presenting, ethereal, pale translucent features"),
    ("a lumberjack in a red plaid flannel shirt, worn jeans, heavy work boots, leather suspenders, and carrying a large axe over one shoulder",
     "masculine-presenting, broad, with Canadian Scandinavian features"),
    ("a kitsune fox spirit in human form wearing a traditional miko outfit — white kosode, red hakama, tabi socks, zori sandals, with visible fox ears and three fluffy tails",
     "feminine-presenting, playful, with Japanese features"),
    ("a deep sea anglerfish person with a bulbous humanoid head, bioluminescent lure, sharp teeth, a dark diving suit, webbed hands, and flipper boots",
     "androgynous deep-sea creature, unsettling glow"),
    ("a vintage circus strongman in a leopard-print unitard, a curled waxed mustache, a wide leather belt, bare feet, and hoisting a huge barbell",
     "masculine-presenting, burly, with handlebar mustache"),
    ("a celestial being whose body is made of the night sky — deep blue translucent form with glowing star patterns, a nebula scarf, and a crescent moon crown",
     "androgynous cosmic being, radiant"),
    ("a Dutch Golden Age merchant in a black doublet with a large white ruff collar, puffed breeches, black stockings, buckled shoes, and a wide-brimmed hat",
     "masculine-presenting, dignified, with Dutch features"),
    ("a baby owl wizard with huge round eyes, a tiny feathered body, a miniature pointed wizard hat, a purple cape, and a tiny wand in one wing",
     "androgynous baby owl character, adorable"),
    ("a parkour runner in sleek athletic compression gear, lightweight trail runners, fingerless gloves, a small running pack, and a focused expression",
     "masculine-presenting, agile, with French Algerian features"),
    ("an Aztec jaguar warrior in a jaguar pelt costume with the jaguar head as a helmet, obsidian macuahuitl sword, round feathered shield, and wooden sandals",
     "masculine-presenting, fierce, with Mesoamerican features"),
    ("a sentient lamp post character with a thin wrought-iron body, a glowing bulb head, thin wire arms, a tiny door in the chest, and cobblestone base for feet",
     "androgynous object character, whimsical"),
    ("a K-pop idol in an oversized designer jacket, a crop top, leather pants, chunky platform sneakers, layered silver chains, and styled two-tone hair",
     "masculine-presenting, trendy, with Korean features"),
    ("a shadow assassin made of living darkness with a smooth featureless black body, glowing white eyes, wisps of shadow trailing, and twin daggers",
     "androgynous shadow creature, menacing"),
    ("a grandpa fisherman bear standing upright in a knitted fisherman's sweater, waders, a bucket hat, tall rubber boots, and holding a fishing rod",
     "masculine-presenting bear character, grandfatherly"),
    ("a solarpunk gardener in a living-plant-embedded vest of moss, vine-wrapped arms, recycled fabric pants, sandals made of bark, and a wide hat with a small solar panel",
     "non-binary-presenting, warm, with African features"),
    ("a heavy metal guitarist in a black spiked leather jacket, torn leather pants, spiked boots, studded wristbands, face paint, and a flying V guitar",
     "masculine-presenting, wild, with long black hair"),
    ("a Vietnamese quan ho singer in an ao tu than four-panel silk dress with a wide belt sash, a conical non la hat, and carrying a folding fan",
     "feminine-presenting, melodious, with Vietnamese features"),
    ("a carnival queen in an ornate feathered samba costume, jeweled bikini top and briefs, platform heels, elaborate headdress, and glittering body paint",
     "feminine-presenting, radiant, with Brazilian features"),
    ("a Scottish bagpiper in a traditional kilt, knee-length socks with red flashes, a sporran, ghillie brogues, a tartan sash, and holding bagpipes",
     "masculine-presenting, proud, with Scottish features"),
    ("a Maasai warrior in traditional red shuka cloth wrapped across the shoulder, leather sandals, beaded neck collars, carrying a long wooden spear",
     "masculine-presenting, tall and lean, with Kenyan Maasai features"),
    ("an Inuit hunter in a thick fur parka with fur-trimmed hood, sealskin boots, mittens, a carved bone knife in the belt, and a harpoon",
     "masculine-presenting, weathered, with Inuit features"),
    ("a flamenco dancer in a ruffled red polka-dot dress with a long train, black high-heeled shoes, a red rose in the hair, and castanets",
     "feminine-presenting, fiery, with Spanish features"),
    ("a Japanese yokai kappa standing upright — green reptilian skin, webbed hands and feet, a water-filled dish on the head, a simple loincloth, and carrying a fish",
     "androgynous yokai creature, mischievous"),
    ("a Tibetan monk in deep maroon and saffron robes, simple leather sandals, a shaved head, wooden prayer beads on the wrist, and hands in a mudra",
     "masculine-presenting, serene, with Tibetan features"),
    ("a West African griot musician in a flowing boubou with gold embroidery, a matching cap, leather sandals, and a kora held upright",
     "masculine-presenting, regal, with Senegalese features"),
    ("a roboticist inventor in a lab coat over a shirt and tie, safety goggles pushed up, rubber gloves, and holding a screwdriver next to a small floating drone",
     "non-binary-presenting, inventive, with South Asian features"),
    ("a punk rocker in a ripped band t-shirt, plaid miniskirt, torn fishnet stockings, chunky combat boots, spiked collar, and a tall green mohawk",
     "feminine-presenting, rebellious, with British features"),
    ("a firefighter in a yellow turnout coat, reinforced pants, helmet, thick gloves, steel-toed boots, and carrying an axe",
     "masculine-presenting, strong, with Irish American features"),
    ("a stage magician in a black tuxedo with tails, a top hat, a red-lined cape, white gloves, a wand, and a rabbit peeking from the hat",
     "masculine-presenting, suave, with handlebar mustache"),
    ("a Venetian carnival performer in a bauta mask, a tricorn hat, a long black cloak, fine breeches, white stockings, and buckled shoes",
     "androgynous, mysterious, masked features"),
    ("a coconut palm tree creature standing upright — a textured brown trunk body, green frond arms, coconut ornaments, root feet, and a cheerful face",
     "androgynous plant creature, sunny"),
    ("a cottagecore farmer's daughter in a linen puff-sleeve blouse, a long gingham skirt, a woven straw basket on the arm, lace-up ankle boots, and flower crown",
     "feminine-presenting, wholesome, with freckled pale skin"),
    ("a Maori warrior with a traditional piupiu flax skirt, bare chest with intricate tā moko tattoos, bone pendant, bare feet, and holding a carved taiaha staff",
     "masculine-presenting, powerful, with Maori features"),
    ("a retro-futurist astronaut in a chrome streamlined space suit with fishbowl helmet, a tall antenna, bulbous boots, and holding a ray gun",
     "masculine-presenting, 1950s scifi aesthetic, square jaw visible through visor"),
    ("a Russian ballet noble in a red velvet dress with gold trim, pearl necklace, heeled Mary Janes, elbow gloves, and a feathered fan",
     "feminine-presenting, regal, with Russian features"),
    ("a jazz saxophonist in a sharp pinstripe suit, a fedora tilted low, two-tone oxford shoes, suspenders visible under the jacket, and a tenor saxophone",
     "masculine-presenting, smooth, with Black features"),
    ("a naval admiral in a pristine white uniform with gold epaulettes, a peaked cap, medals on the chest, white gloves, polished black shoes",
     "masculine-presenting, commanding, with Eastern European features"),
    # --- Expanded pool (for SC-201+) ---
    ("a renaissance fair jester in a motley red and yellow tunic, striped hose, curly-toed shoes, a belled cap, and juggling three colored balls",
     "masculine-presenting, playful, with freckled pale skin"),
    ("a rockabilly pinup mechanic in rolled-up denim overalls over a knotted gingham shirt, red bandana in the hair, ankle boots, holding a wrench",
     "feminine-presenting, confident, with 1950s American features"),
    ("a Byzantine empress in a long embroidered stola, a jeweled diadem with pendulia, purple robe trimmed in gold, sandal-boots, and holding a cross scepter",
     "feminine-presenting, imperial, with Anatolian features"),
    ("a gas station attendant in coveralls with a name patch, baseball cap, work boots, grease-stained hands, and holding a rag",
     "masculine-presenting, friendly, with Southern American features"),
    ("a sushi chef in crisp white uniform, sushi headband, navy apron, wooden geta sandals, and holding a large sharp knife",
     "masculine-presenting, precise, with Japanese features"),
    ("a fallen angel in tattered dark robes, one broken charcoal wing, bare dirty feet, a snapped halo, and melancholy eyes",
     "androgynous, sorrowful, with ashen skin"),
    ("a 1990s mall goth in a black mesh crop top, plaid mini skirt, striped knee socks, chunky platform boots, and a choker necklace",
     "feminine-presenting, moody, with dyed black hair"),
    ("a stout dwarven smith with a long braided beard, a heavy leather apron, hammer in one hand, forge-scorched gauntlets, and iron-shod boots",
     "masculine-presenting, stocky, with ruddy Scottish features"),
    ("a forest elf archer in fitted green leathers, a hooded cloak of living leaves, bare feet, a compound bow, and glowing eyes",
     "androgynous, elegant, with pointed ears and silver-streaked hair"),
    ("a Berber caravan trader in a flowing indigo robe, a deep blue turban covering the face, leather sandals, silver jewelry, and a camel whip",
     "masculine-presenting, weathered, with Saharan features"),
    ("a motorcycle rider in a black leather jacket, riding pants, heavy boots, full-face helmet under one arm, and riding gloves",
     "feminine-presenting, tough, with Latina features"),
    ("a gothic vampire in a long black Victorian coat with red lining, high collar, pale skin, fangs visible, pointed boots, and a silver-topped cane",
     "masculine-presenting, aristocratic, with pale English features"),
    ("a Japanese onmyoji in traditional eboshi hat and sokutai robes, paper talismans in one hand, wooden sandals, and a serious expression",
     "masculine-presenting, mystical, with Heian-era Japanese features"),
    ("a punk princess with a pastel pink spiked jacket, tulle tutu, combat boots, a rhinestone tiara, and a ripped band t-shirt",
     "feminine-presenting, rebellious, with alternative style"),
    ("a Navajo sheepherder in a velveteen shirt, long skirt, silver concha belt, moccasins, turquoise jewelry, and holding a shepherd's crook",
     "feminine-presenting, dignified, with Navajo features"),
    ("a boxer in satin shorts, boxing shoes, hand wraps, a championship belt slung over the shoulder, and a protective mouthguard",
     "masculine-presenting, athletic, with Cuban features"),
    ("a gondolier in the traditional striped shirt, dark trousers with a sash, straw boater hat with ribbon, rope shoes, and wielding an oar",
     "masculine-presenting, friendly, with Italian features"),
    ("a priestess of the moon in silver-trimmed white robes, a crescent diadem, bare feet, a staff with a moonstone, and flowing white hair",
     "feminine-presenting, ethereal, with pale translucent skin"),
    ("a cheerful postal worker in a blue uniform, peaked cap, shorts, sneakers, a shoulder mail bag, and holding a small package",
     "non-binary-presenting, energetic, with mixed-race features"),
    ("a feudal Korean royal guard in traditional hwangho armor, a red tasseled helmet, leather boots, holding a ceremonial spear",
     "masculine-presenting, stoic, with Korean features"),
    ("a coral reef mermaid warrior with vivid coral-patterned scales, clamshell bra, shark-tooth spear, and flowing blue-green hair",
     "feminine-presenting, fierce, with Pacific Islander features"),
    ("a stressed office worker in a wrinkled business suit, loose tie, scuffed shoes, carrying a coffee cup and a messy stack of papers",
     "masculine-presenting, harried, with balding pale features"),
    ("a tiny fairy in a dress made of overlapping flower petals, translucent insect wings, bare feet, tiny twig wand, and glowing dust trailing",
     "feminine-presenting, delicate, with pointed ears and tiny stature"),
    ("a Zulu warrior with a traditional leopard-skin headband, cowhide shield, assegai spear, beaded ornaments, and bare chest with iklwa",
     "masculine-presenting, powerful, with Zulu features"),
    ("an Orthodox priest in long black robes with a ryasa tunic, tall klobuk hat, thick beard, pectoral cross, and leather sandals",
     "masculine-presenting, solemn, with Greek features"),
    ("a cute zombie girl in a torn prom dress, one arm hanging loose, a party tiara askew, mismatched patent shoes, and pale grey skin",
     "feminine-presenting, kawaii undead, with stitches visible"),
    ("a chimney sweep child in sooty ragged clothes, a flat cap, worn shoes, a long brush slung over the shoulder, and grime-smudged face",
     "masculine-presenting, scrappy, with Victorian English features"),
    ("a Persian cat noble standing upright in a silk Qajar-style long coat, embroidered vest, pointed shoes, and a jeweled turban",
     "androgynous cat character, aristocratic"),
    ("a country singer in rhinestone cowboy boots, fringed leather jacket, denim shirt, wide belt buckle, cowboy hat, and an acoustic guitar",
     "feminine-presenting, warm, with Texan features"),
    ("a chef hat mushroom creature with a giant cap head, thin stalk body, four tiny arms, moss beard, and tiny leaf slippers",
     "androgynous plant creature, whimsical"),
    ("a Balinese dancer in an ornate gold-brocade tapih skirt, a tall gilded crown, pointed finger extensions, tight bodice, and ornate earrings",
     "feminine-presenting, graceful, with Balinese features"),
    ("an ice cream truck vendor in a pastel striped apron, paper cap, white pants, bright sneakers, and holding two ice cream cones",
     "feminine-presenting, cheerful, with Italian American features"),
    ("a Viking shieldmaiden with braided red hair, chainmail over a green tunic, leather boots, round wooden shield, and a notched battle axe",
     "feminine-presenting, fierce, with Scandinavian features"),
    ("a rainbow-scaled sea dragon girl standing on two clawed feet, iridescent scales, a simple wrap dress, long finned ears, and sharp claws",
     "feminine-presenting dragon creature, whimsical"),
    ("a surly librarian in a pencil skirt, cardigan, sensible heels, cat-eye glasses on a chain, hair in a tight bun, and clutching several books",
     "feminine-presenting, stern, with pale American features"),
    ("a DJ in a snapback cap, flashy bomber jacket, designer joggers, neon sneakers, headphones around the neck, and hands on a controller",
     "masculine-presenting, cool, with mixed-race features"),
    ("an Egyptian pharaoh in a pleated white linen shendyt skirt, nemes headcloth with gold bands, ornate collar, sandals, and a crook and flail",
     "masculine-presenting, regal, with Egyptian features"),
    ("a 1950s greaser in a white t-shirt, leather jacket, cuffed blue jeans, black boots, slicked-back pompadour, and a cigarette tucked behind the ear",
     "masculine-presenting, rebellious, with Italian American features"),
    ("a swamp fairy with pond-algae green skin, a dress of lily pads, pixie-cut mossy hair, bare webbed feet, and dragonfly wings",
     "feminine-presenting, mischievous, with reedy figure"),
    ("a Peruvian alpaca herder in a colorful striped poncho, woven chullo hat with ear flaps, sturdy sandals, carrying a small alpaca toy",
     "masculine-presenting, gentle, with Andean features"),
    ("a paramedic in a navy uniform, reflective vest, steel-toed boots, trauma kit slung over shoulder, and a radio on the shoulder",
     "feminine-presenting, professional, with pale freckled skin"),
    ("a samurai oni (demon warrior) with red skin, horns, bulging eyes, ornate lacquer armor, a kanabo club, and bare feet",
     "masculine-presenting, monstrous, with traditional oni features"),
    ("a suburban mom in athleisure wear — cropped leggings, zip-up jacket, sneakers, messy bun, large coffee tumbler, and a diaper bag",
     "feminine-presenting, busy, with Midwestern American features"),
    ("a Polynesian fire dancer in a grass skirt, shell lei, tattoos, bare feet, and holding a flaming poi on a chain",
     "masculine-presenting, athletic, with Samoan features"),
    ("a librarian robot with a boxy metal body, book-slot chest, spindly arms, a screen for a face, wheel feet, and holding a scanned book",
     "gender-ambiguous robot character"),
    ("a lighthouse ghost in a long-dead sailor's uniform, tattered peacoat, phantom peg leg, spectral lantern, and translucent form",
     "masculine-presenting, melancholy, with ghostly form"),
    ("a fantasy gnome alchemist with a pointed red hat, a stained robe belted with potion vials, tall boots, a long white beard, and a bubbling flask",
     "masculine-presenting, tiny, with ruddy cheeks and bulbous nose"),
    ("a Filipino barangay captain in a barong tagalog shirt, dark slacks, leather shoes, an official sash, and holding a rolled document",
     "masculine-presenting, confident, with Filipino features"),
    ("a mermaid merchant with a clam-shell cash register, a pearl necklace, a kelp satchel filled with goods, tail curled, and gold rings on the tail",
     "feminine-presenting, friendly, with island features"),
    ("a veterinary surgeon in blue scrubs, surgical cap, booties, latex gloves, carrying a puppy in one arm and stethoscope around the neck",
     "non-binary-presenting, caring, with Dutch features"),
    ("a desert djinn emerging from a lamp — smoky lower body instead of legs, muscular torso, golden bracers, turban with a sapphire, and crossed arms",
     "masculine-presenting, imposing, with smoke-colored skin"),
    ("a 1920s flapper in a fringed beaded dress, T-strap heels, a feathered headband, long pearl necklace, and holding a long cigarette holder",
     "feminine-presenting, glamorous, with bobbed dark hair"),
    ("a miniature gnome gardener in rubber boots way too big, green overalls, a pointed red cap, a trowel over the shoulder, and a bag of seeds",
     "androgynous gnome character, tiny"),
    ("an arctic explorer in a fur-trimmed parka, snow pants, insulated boots, tinted goggles, a thick scarf, and carrying ski poles",
     "masculine-presenting, tough, with Norwegian features"),
    ("a Japanese mecha pilot in a skintight pilot suit with plug suit accents, utility belt, harness, mid-calf boots, and helmet held under one arm",
     "feminine-presenting, focused, with East Asian features"),
    ("a hippie traveler in tie-dye shirt, wide-leg linen pants, hemp sandals, headband, macrame bag, and playing a small wooden flute",
     "non-binary-presenting, peaceful, with long hair and beads"),
    ("a plague doctor in a long waxed cloak, a bird-beaked mask, wide-brimmed hat, gloves, tall boots, and a walking staff",
     "gender-ambiguous, mysterious, mask hides features"),
    ("a cute fox girl in a red kimono with fox-tail patterns, wooden sandals, a hair ornament shaped like leaves, and fluffy fox tail and ears",
     "feminine-presenting, playful, with Japanese features and kitsune traits"),
    ("a Middle Eastern belly dancer in a coin-covered bra, low-slung pantaloons, bare feet, bangles stacked on the wrists, and a diaphanous veil",
     "feminine-presenting, sensual, with Lebanese features"),
    ("a cattle rustler in a duster coat, spurred boots, chaps, a bandana pulled up, a revolver, and a coiled lasso over the shoulder",
     "masculine-presenting, gritty, with American West features"),
    ("a porcelain doll character with jointed painted-porcelain skin, Victorian dress with lace trim, Mary Jane shoes, ringlet curls, and glass eyes",
     "feminine-presenting, uncanny, with cracked porcelain skin"),
    ("a tattoo artist in a sleeveless black shirt showing full sleeve tattoos, ripped black jeans, Vans, a septum ring, and holding a tattoo gun",
     "non-binary-presenting, edgy, with shaved sides and colored hair"),
    ("a mountain shaman in layered leather and bone robes, feathered headdress, bear-claw necklace, moccasin boots, and holding a ritual rattle",
     "masculine-presenting, ancient, with weathered Indigenous features"),
    ("a cute corgi knight standing on two hind legs in miniature chainmail, a red cape, a toothpick sword, and a little helm askew",
     "androgynous corgi character, plucky"),
    ("a tech startup founder in a fitted hoodie with a company logo, jeans, white sneakers, a smartwatch, and holding a tablet with charts",
     "masculine-presenting, driven, with East Asian features"),
    ("a grim reaper in a tattered black robe with a deep hood, skeletal hands visible, a towering scythe, and pale bone-white feet",
     "androgynous, ominous, with skeletal features"),
    ("a Bavarian maiden in a dirndl with puff sleeves, a red-and-white-checked apron, thigh-high socks, lace-up ankle boots, and floral hair wreaths",
     "feminine-presenting, cheerful, with Germanic features"),
    ("a military sniper in woodland ghillie suit, helmet with foliage, tactical gloves, combat boots, a long-range rifle, and face paint",
     "gender-ambiguous, camouflaged"),
    ("a Thai nang kwak beckoning-lady statue come to life — gold skin, long traditional gold-brocade dress, tall temple headdress, and arm raised in greeting",
     "feminine-presenting, divine, with gilded skin"),
    ("a dapper gentleman frog standing upright in a tiny waistcoat, monocle, bowler hat, tweed trousers, brogues, and a walking cane",
     "masculine-presenting frog character, refined"),
    ("a nurse in pink scrubs, a name badge, stethoscope around the neck, white clogs, hair in a neat bun, and carrying a clipboard",
     "feminine-presenting, warm, with Filipino features"),
    ("a swashbuckling musketeer in a blue tabard with a cross, plumed hat, long boots with folded tops, a baldric, and a rapier held aloft",
     "masculine-presenting, dashing, with French features"),
    ("a bartender in suspenders over a crisp white shirt, rolled sleeves, a waist apron, polished dress shoes, a pencil mustache, and shaking a cocktail",
     "masculine-presenting, suave, with Italian features"),
    ("a snow leopard person in thick mountaineer furs, climbing axe, crampon boots, a scarf, with leopard-print spotted fur patterns on the face",
     "androgynous beastkin character, mountainous"),
    ("a Tudor queen in a farthingale gown with a square neckline, a gabled hood, pearl necklaces, heeled Mary Janes, and holding a handkerchief",
     "feminine-presenting, regal, with pale English features"),
    ("a mariachi musician in a traditional charro suit with silver buttons down the trousers, wide sombrero, boots, a red bowtie, and a trumpet",
     "masculine-presenting, festive, with Mexican features"),
    ("a giant sunflower person with a sunflower-head face, green stem body, broad leaf hands, earthen pot feet, and a simple floral sundress",
     "androgynous plant character, cheerful"),
    ("a Burmese Buddhist nun in pink robes, a saffron sash, simple sandals, a shaved head, a begging bowl, and prayer beads",
     "feminine-presenting, serene, with Burmese features"),
    ("a glitchy digital ghost in pixelated purple and green, parts of the body missing, glitch artifacts, floating slightly, and translucent static form",
     "androgynous digital entity, unstable"),
    ("a Pacific Northwest logger in a wool vest, Frisco jeans, calked boots, a hard hat, suspenders, a massive beard, and carrying a two-man saw",
     "masculine-presenting, huge, with Canadian features"),
    ("a Victorian spiritualist in a high-necked black mourning dress, a cameo brooch, a long lace veil pinned back, tall boots, and a spirit board tucked under one arm",
     "feminine-presenting, haunted, with pale English features"),
    ("a kappa turtle person — green skin, a turtle shell on the back, webbed feet, a dish of water on the head, simple wrap shorts, and a small fish in hand",
     "androgynous yokai character, mischievous"),
    ("a climbing enthusiast in stretchy pants, a sports bra, chalk bag, climbing shoes, helmet, and a rope coil over one shoulder",
     "feminine-presenting, athletic, with pale athletic features"),
    ("a sultan in a jeweled turban with a sapphire, an embroidered kaftan, gold-trimmed slippers, a pearl-studded belt, and a scimitar",
     "masculine-presenting, opulent, with Ottoman features"),
    ("a kid in a dinosaur onesie — green hooded outfit with fabric spines, puffy feet pads, mittens, and peeking out from the hood",
     "androgynous child character, playful"),
    ("a 17th-century Spanish conquistador in a steel morion helmet, breastplate, puffed sleeves, tall boots, and gripping a cross-hilted sword",
     "masculine-presenting, stern, with Spanish features"),
    ("a cotton candy cloud person — fluffy pink body, whipped cream hair, candy stick arms, tiny boots, a sugar-spun skirt, and a twinkling face",
     "androgynous sweet creature, dreamy"),
    ("a martial arts monk in orange robes tied with a black belt, a shaved head, wooden sandals, and wielding a bo staff in a ready stance",
     "masculine-presenting, focused, with Chinese features"),
    ("a vintage stewardess in a pillbox hat, slim-line dress with white gloves, kitten heels, a handbag, and a small suitcase",
     "feminine-presenting, poised, with Pan Am era aesthetic"),
    ("a phoenix-woman with flowing fiery red-and-gold robe-feathers, golden eyes, crown of flame, bare ember-feet, and wings unfolding from her back",
     "feminine-presenting, radiant, with flame-colored hair"),
    ("a hot-dog vendor in a striped apron, paper cap, white pants, mustard-stained shirt, sneakers, and waving a pair of tongs",
     "masculine-presenting, New Yorker, with Greek features"),
    ("a spirit of the forest deer-human hybrid — deer legs, a humanoid torso, antlers crowned with flowers, bare moss-covered chest, and glowing eyes",
     "androgynous forest creature, ethereal"),
    ("a Tibetan yak herder in thick yak-wool robes, fur-lined boots, a felt hat with side flaps, leather belt, and carrying a wooden staff",
     "masculine-presenting, rugged, with Tibetan features"),
    ("a 2000s punk skater girl in a band tee, ripped fishnets under denim shorts, a studded belt, checkered Vans, and a skateboard under one arm",
     "feminine-presenting, rebellious, with piercings and colored hair tips"),
    ("a Hindu raja in a gold-bordered sherwani, embroidered shawl draped across the chest, pointed juttis, a bejeweled turban, and a jeweled dagger",
     "masculine-presenting, royal, with North Indian features"),
    ("a cotton-eared bunny girl in a lace-trimmed maid dress, a white apron, thigh-high stockings, Mary Janes, fluffy pink ears, and a small fluffy tail",
     "feminine-presenting, cute, with pastel hair and anime proportions"),
    ("a Polish hussar with oversized feathered wings on the back, plate armor, fur-trimmed cape, tall boots, and holding a long lance",
     "masculine-presenting, heroic, with Polish features"),
    ("a tiny robot child with a boxy head, large camera-lens eyes, segmented arms, rolling ball feet, a little backpack, and holding a stuffed toy",
     "androgynous tiny robot, innocent"),
    ("a beekeeper in a full white protective suit with mesh veil hat, thick gloves, boots, holding a smoker, and bees floating around",
     "masculine-presenting, calm, with Eastern European features"),
    ("a Bulgarian folk dancer in a white embroidered shirt, red vest, full pleated skirt, red sash, traditional tsarvuli leather shoes, and flower crown",
     "feminine-presenting, cheerful, with Balkan features"),
    ("a demon hunter in tight leather armor with silver crosses, a crossbow, a longcoat, tall boots, fingerless gloves, and a scar over one eye",
     "feminine-presenting, grim, with Eastern European features"),
    ("a royal pastry chef in a tall white toque, double-breasted jacket, checkered pants, clogs, and holding a piping bag decorating an invisible cake",
     "masculine-presenting, proud, with French features"),
    ("an angler fish woman — glowing lure on the forehead, sharp teeth, long wet hair, a tattered deep-sea dress, and webbed hands holding a rusted lantern",
     "feminine-presenting, eerie, with bluish pale skin"),
    ("a Scottish warrior woman in a tartan kilted dress, leather bodice, wool wrap, knee-high boots, war paint on the face, and wielding a claymore",
     "feminine-presenting, fierce, with Scottish features"),
    ("a paperboy from the 1930s in knee-length trousers, suspenders, a flat newsboy cap, scuffed shoes, a shoulder bag full of papers, and waving one",
     "masculine-presenting, scrappy, with Chicago features"),
    ("a wandering bard in a patchwork cloak, a lute strapped to the back, feathered hat, leather pants, comfortable boots, and singing",
     "masculine-presenting, charismatic, with Mediterranean features"),
    ("a seraph angel with six wings (two covering the face, two the body, two spread wide), white robe, gold halo, and holding a sword of light",
     "androgynous celestial, radiant"),
    ("a 1970s rock groupie in a fringed suede vest, bell-bottom jeans, platform heels, peace-sign necklaces, big hair, and a Polaroid camera",
     "feminine-presenting, free-spirited, with sun-kissed hair"),
    ("a mech pilot mid-stride toward their giant robot in a form-fitting flight suit, helmet tucked under arm, boots, a shoulder patch insignia",
     "feminine-presenting, focused, with East Asian features"),
    ("a peasant farmer girl in a simple hemp dress, a straw hat with a ribbon, bare feet with hay stuck to them, a wicker basket of wheat on the hip",
     "feminine-presenting, humble, with rustic European features"),
    ("an assassin nun in a tight black habit, a veil, a stiletto strapped to the thigh, combat boots, and a rosary wrapped around the wrist",
     "feminine-presenting, lethal, with Italian features"),
    ("a bullet-train conductor in a navy uniform with red trim, a peaked cap, white gloves, polished shoes, and a pocket watch",
     "masculine-presenting, proud, with Japanese features"),
    ("a Viking shaman with a horned skull helmet, layered animal pelts, bare chest with rune tattoos, bone necklaces, and a staff topped with a raven skull",
     "masculine-presenting, wild, with long tangled hair"),
    ("a sophisticated lady cat in a floor-length evening gown, elegant opera gloves, pearl choker, high heels, long feather boa, and a martini glass",
     "feminine-presenting cat character, glamorous"),
    ("a Kyiv dragoon cavalier in a wool cap with a red band, long greatcoat, leather saber belt, tall cavalry boots, and carrying a curved sabre",
     "masculine-presenting, proud, with Ukrainian features"),
    ("a surly prison guard in a black uniform with utility belt, knee-high boots, aviator sunglasses, a baton, a key ring, and a walkie-talkie",
     "masculine-presenting, stern, with shaved head"),
    ("a ghost pirate captain in an 18th-century uniform turned translucent blue, a spectral cutlass, torn tricorn, phantom peg leg, and glowing lantern",
     "masculine-presenting, menacing, with ghostly form"),
    ("a Mexican Day of the Dead bride in a flowing white lace dress, skull face paint, flower crown, long veil, bare feet, and holding a wilted bouquet",
     "feminine-presenting, haunting, with Mexican features"),
    ("a cactus gunslinger — cactus-body humanoid with spines, a poncho draped over the shoulder, cowboy hat, wooden sandals, and two six-shooters",
     "androgynous plant character, badass"),
    ("a Hindu Kathak dancer in a lehenga choli with mirror-work, long dupatta, ankle bells (ghungroo), hands in a mudra pose, and ornate jewelry",
     "feminine-presenting, precise, with North Indian features"),
    ("a Wild West saloon owner in a red velvet suit with a gold watch chain, ruffled shirt, waistcoat, polished shoes, a handlebar mustache, and a cane",
     "masculine-presenting, theatrical, with period features"),
    ("an emo high schooler in tight black jeans, a band hoodie, converse, side-swept bangs covering one eye, studded belt, and drawing on a backpack",
     "androgynous, brooding, with mid-2000s style"),
    ("a Roman vestal virgin in a white stola with a purple hem, a head covering (suffibulum), simple leather sandals, holding a ceremonial torch",
     "feminine-presenting, serene, with Italian features"),
    ("a bodybuilder posing in competition briefs, oiled tan skin, sculpted muscles, and striking a most-muscular pose with veins visible",
     "masculine-presenting, massive, with competition-ready physique"),
    ("a jester pumpkinhead in a harlequin suit, a carved pumpkin for a head with a flickering candle inside, curly-toed shoes, and belled gloves",
     "androgynous spooky creature, whimsical"),
    ("a 19th-century Japanese jinrikisha runner in a loincloth, straw sandals, a headband, bare chest, and holding the shafts of an implied rickshaw",
     "masculine-presenting, lean, with Meiji-era features"),
    ("a space-miner in a beat-up mech-suit with exposed hydraulics, helmet off revealing a grease-smudged face, carrying a heavy pneumatic drill",
     "non-binary-presenting, tough, with grease-smudged features"),
    ("a celestial ox god in traditional Chinese warrior armor, ox horns, human body, bull's tail, holding a glaive, and a red sash flowing",
     "masculine-presenting, divine, with Chinese mythology features"),
    ("a Slavic Rusalka water spirit in a translucent dripping white gown, long tangled water-weed hair, bare feet not touching the ground, glowing eyes",
     "feminine-presenting, eerie, with pale drowned features"),
    ("a pet shop worker in a polo shirt with a shop logo, jeans, sneakers, a small clipboard, and carrying a shy puppy in the arms",
     "non-binary-presenting, cheerful, with freckled mixed-race features"),
    ("a Sami reindeer herder in a bright blue gákti tunic with red and yellow trim, leather boots, a reindeer hide cape, and holding a lasso",
     "masculine-presenting, weathered, with Northern European features"),
    ("a Mesoamerican rain god in green feathered attire, turquoise jade beads, a long-nosed ceremonial mask, and holding a lightning-bolt scepter",
     "masculine-presenting, divine, with ceremonial face paint"),
    ("an astronaut botanist in a modified space suit with an open helmet, plant containers, a spray bottle, garden gloves, and holding a small potted sprout",
     "feminine-presenting, curious, with afro-textured hair"),
    ("a werewolf girl mid-transformation — partly wolfish snout, furry arms, claws, torn sleeveless dress, bare hairy legs, and glowing yellow eyes",
     "feminine-presenting, feral, with transformation in progress"),
    ("a retro lifeguard in classic red swim trunks, a whistle on a lanyard, aviator sunglasses, zinc sunscreen on the nose, and carrying a rescue buoy",
     "masculine-presenting, fit, with sun-bleached hair"),
    ("a Tengu mountain spirit in ornate ceremonial robes, tall geta, a red long-nosed mask, feathered collar, and holding a feather fan",
     "masculine-presenting, supernatural, with Japanese features"),
    ("a goth loli in a black-and-white frilled dress with ribbons, knee socks, Mary Janes, a parasol, a headdress bow, and twin drill-curl hair",
     "feminine-presenting, elegant, with porcelain skin"),
    ("a Nepalese Sherpa guide in a down jacket over a wool sweater, thick trekking pants, heavy boots, a backpack with an ice axe, and snow goggles",
     "masculine-presenting, strong, with Tibetan-Nepali features"),
    ("an evil king in spiked black armor, a massive crown dripping with gemstones, a fur-trimmed cape, clawed gauntlets, and a cruel-looking sword",
     "masculine-presenting, tyrannical, with gaunt pale features"),
    ("a petite kindergarten teacher in a pastel cardigan, a pencil skirt, flats, a name tag, holding a picture book open, and a pencil behind the ear",
     "feminine-presenting, gentle, with Korean features"),
    ("a Jamaican rastafarian elder in a red, gold, green tam hat over long dreadlocks, a loose linen shirt, cargo pants, sandals, and holding a wooden staff",
     "masculine-presenting, peaceful, with long white beard"),
    ("a centaur archer with a horse body (chestnut brown) and human upper body, leather cross-belts, quiver on the back, and holding a curved bow",
     "masculine-presenting, muscular, with long brown hair"),
    ("a mad queen in a disheveled royal gown with torn lace, a crooked crown, bare dirty feet, smeared makeup, and holding a shattered mirror",
     "feminine-presenting, unhinged, with wild hair"),
    ("a Korean hanbok noble in a silk jeogori jacket with wide sleeves, a voluminous chima skirt, norigae pendants, traditional shoes, and a fan",
     "feminine-presenting, refined, with Korean features"),
    ("a gym coach in a track suit, whistle around the neck, baseball cap, sneakers, clipboard, stopwatch, and pointing with authority",
     "masculine-presenting, loud, with retired-athlete build"),
    ("a Kenyan safari guide in khaki shorts and shirt, a wide-brim hat, binoculars around the neck, hiking boots, and carrying a walking stick",
     "masculine-presenting, knowledgeable, with Kenyan features"),
    ("a tiny harvest gnome in a pointed orange hat, a green tunic, pumpkin-vine belt, tiny leather boots, and carrying a basket of apples",
     "androgynous gnome character, friendly"),
    ("a cult leader in white linen robes, bare feet, a serene smile, a pendant of unknown symbol, long flowing hair, and arms spread wide in welcome",
     "androgynous, unsettling, with too-calm features"),
    ("a Scottish highland dancer in a kilted skirt, waistcoat over a white blouse, knee socks with ghillies, tartan sash pinned at the shoulder, and jig stance",
     "feminine-presenting, graceful, with Scottish features"),
    ("a ronin samurai without a master in a tattered kimono, worn straw hat, katana at hip, bare dirty feet in broken straw sandals, and haunted eyes",
     "masculine-presenting, weary, with long unkempt hair"),
    ("a TikTok dancer in a coordinated crop top and bike shorts, sparkly sneakers, hair in two space buns, a smartwatch, and mid-dance pose",
     "feminine-presenting, trendy, with Gen-Z aesthetic"),
    ("a medieval nun in a black habit with a white wimple, rosary beads around the waist, sandals, hands folded in prayer at the chest",
     "feminine-presenting, devout, with pale European features"),
    ("a frog prince transformed halfway — still mostly frog with a small gold crown, a tiny velvet cape, and a single human hand reaching out",
     "androgynous frog prince, whimsical"),
    ("a Ghanaian Ashanti king in a kente cloth wrapped across one shoulder, gold ornaments, a beaded crown, leather sandals, and holding a royal sword",
     "masculine-presenting, dignified, with Ghanaian features"),
    ("a Cajun bayou guide in hip waders, a flannel shirt, a weather-beaten cap, a machete on the belt, rubber boots, and holding a lantern",
     "masculine-presenting, weathered, with Creole features"),
    ("a moonlit fox demon in a black kimono with silver moon embroidery, nine flowing fox tails, fox ears, wooden geta, and pale blue fire floating around",
     "androgynous kitsune character, beautiful and dangerous"),
    ("a vintage 1950s baseball player in a wool uniform with striped socks, cleats, a classic cap, a leather glove, and holding a wooden bat",
     "masculine-presenting, all-American, with clean-cut features"),
    ("a silver dragon warrior in iridescent scale armor, a horned helmet, a long flowing tail behind, clawed gauntlets, and wielding a massive halberd",
     "androgynous dragon warrior, imposing"),
    ("a plague scholar in tattered academic robes, a heavy book chained to the wrist, a bird-beaked mask pushed up showing sickly features, and a crutch",
     "gender-ambiguous, haunted"),
    ("a roller derby skater in fishnet tights, padded shorts, an athletic jersey with number, knee pads, elbow pads, helmet with stickers, and roller skates",
     "feminine-presenting, fierce, with bright tattoos"),
    ("a Galactic Republic ambassador in a flowing senator's robe with gold embroidery, a high collar, elaborate headdress, soft boots, and a datapad",
     "feminine-presenting, poised, with cosmic otherworldly features"),
    ("a scruffy mountain man in bear-fur clothes, a homemade leather cap, heavy boots, a thick braided beard, and carrying a flintlock rifle",
     "masculine-presenting, burly, with weathered features"),
    ("a Balinese rice farmer in a straw conical hat, a white shirt with rolled sleeves, sarong tied at the waist, bare feet, and carrying a sickle",
     "masculine-presenting, gentle, with Indonesian features"),
    ("a Victorian ghost child in a sailor suit (boys) with shorts and knee socks, translucent skin, a floating toy boat, and melancholic eyes",
     "masculine-presenting, ghostly, with pale face"),
    ("a swashbuckling lady pirate in a long coat open to the waist, loose blouse, breeches, thigh-high boots, a tricorn, and a curved cutlass in each hand",
     "feminine-presenting, bold, with Caribbean features"),
    ("an Ethiopian Orthodox priest in a white tunic with a red sash, a tall head cloth, a jeweled cross necklace, leather sandals, and holding a prayer staff",
     "masculine-presenting, holy, with Ethiopian features"),
    ("a galaxy-haired sorceress in a midnight-blue gown dotted with stars, hair that flows like a nebula, bare feet, a crystal wand, and floating auras",
     "feminine-presenting, cosmic, with translucent skin"),
    ("a Senegalese wrestler in a sabar loincloth, bare chest smeared with ceremonial paste, amulets around the neck, bare feet, and a ready stance",
     "masculine-presenting, powerful, with Senegalese features"),
    ("a medieval executioner in a black hood, sleeveless tunic, heavy boots, leather apron, thick gloves, and holding a large two-handed axe",
     "masculine-presenting, brawny, only the eyes visible"),
    ("an elegant mer-prince with a long blue-and-silver tail, chest adorned with gold pauldrons shaped like conch shells, a trident, and flowing silver hair",
     "masculine-presenting, regal, with Polynesian features"),
    ("a scruffy rooftop chimney-dwelling fae in patchwork clothes, one oversized work glove, bare dirty feet, wings like torn paper, and a bent lantern",
     "androgynous urban fae, mischievous"),
    ("a Grecian philosopher in a white toga draped over one shoulder, sandals, a long beard, a scroll in one hand, and a contemplative gaze",
     "masculine-presenting, thoughtful, with classical features"),
    ("a sun priestess in a golden ceremonial gown with a radiating sun headdress, gold bangles, bare feet on a sun-disk amulet, and a golden chalice raised",
     "feminine-presenting, luminous, with Egyptian features"),
    ("a cactus-belly cowgirl — humanoid cactus body, a battered Stetson, a gun belt, red bandana, worn leather boots, and a spinning lasso",
     "feminine-presenting plant creature, flirty"),
    ("a Taino tribal warrior in a woven yucca cotton loincloth, shell necklace, feather headdress, bare feet, body paint, and holding a wooden macana club",
     "masculine-presenting, fierce, with Caribbean Indigenous features"),
    ("a detective from the future in a tech-enhanced trench coat with HUD displays, holographic badge, plasma pistol, boots, and high-tech visor",
     "feminine-presenting, hardboiled, with cybernetic details"),
    ("a Jewish klezmer fiddler in a black suit, waistcoat, kippah, traditional tallit, polished shoes, and playing a violin passionately",
     "masculine-presenting, lively, with Eastern European Jewish features"),
    ("a southern belle in a hoop skirt ballgown with ruffles and lace, elbow-length gloves, a delicate parasol, ringlets, and a painted fan",
     "feminine-presenting, graceful, with antebellum features"),
    ("a mecha-rebel in a patchwork of salvaged armor plates, a targeting visor, tactical harness, painted kneepads, and a large rifle",
     "non-binary-presenting, gritty, with dust-streaked face"),
    ("a tiny hedgehog lady in a floral dress, pearl necklace, tiny handbag, little Mary Janes, and holding a wicker picnic basket",
     "feminine-presenting hedgehog character, prim"),
    ("an alchemist with a long dark robe with silver embroidery of symbols, a tall pointy hood, gloves, leather boots, a flask of glowing liquid, and a grimoire",
     "gender-ambiguous, scholarly, face hidden in hood shadow"),
    ("a 1920s boxer in striped trunks, high laced boxing boots, hand wraps, a slicked-back hairstyle, and fists raised",
     "masculine-presenting, tough, with Irish features"),
    ("a Hawaiian hula dancer in a ti-leaf skirt, a lei of plumeria, kukui-nut bracelets, a coconut-shell bra, bare feet, and arms raised in dance",
     "feminine-presenting, graceful, with Polynesian features"),
    ("a lumber elf with mossy-green hair, twig-and-leaf clothing, bark-like leather armor, a long bow carved from living wood, and bare forest-dusty feet",
     "androgynous forest elf, ancient"),
    ("a fantasy desert nomad queen with layered sand-colored silk veils, a golden nose ring connected to an ear cuff, jeweled belt, and sandal-boots",
     "feminine-presenting, striking, with desert features"),
    ("a steampunk airship captain in a navy double-breasted coat with brass buttons, a cocked hat, goggles pushed up, thigh-high boots, and a saber",
     "feminine-presenting, dashing, with English features"),
    ("an Australian Aboriginal dreamtime spirit in a loincloth, body paint with dot patterns, ceremonial feathers, bare feet, and holding a didgeridoo",
     "masculine-presenting, ancient, with Aboriginal features"),
    ("a college freshman in sweatpants, an oversized university hoodie, Crocs with socks, a backpack, headphones on, and clutching a coffee and laptop",
     "non-binary-presenting, sleepy, with bedhead"),
    ("a silver-scaled Naga serpent priest with a human upper body covered in jeweled pectorals, long snake lower body instead of legs, and a ceremonial staff",
     "masculine-presenting, divine, with Indian features and a cobra hood"),
    ("a demolitions expert in heavy tactical gear, a vest full of pouches, a blast shield helmet tucked under one arm, thick boots, and defusing wires",
     "masculine-presenting, calm, with military haircut"),
    ("a Cuban salsa dancer in a tight red ruffled dress with a thigh-high slit, strappy heels, dangling earrings, and mid-spin dance pose",
     "feminine-presenting, passionate, with Cuban features"),
    ("a necromancer in a hooded robe of dark rags, skull mask pushed to the side of the face, a bone wand, skeletal fingers, and bare feet",
     "androgynous, sinister, with deathly pallor"),
    ("a Shrek-like green ogre in a patched brown tunic, rope belt, rough bare feet, a bulging belly, tusks visible, and a scratchy beard",
     "masculine-presenting ogre character, friendly"),
    ("a Zen painter in a simple gray yukata, a bamboo brush in hand, a straw hat hanging on the back, wooden sandals, and ink-smudged fingers",
     "masculine-presenting, contemplative, with Japanese features"),
    ("a fantasy scholar-priest in layered robes with astrolabe ornaments, a tall academic hat, heavy tomes under one arm, and wire-rimmed spectacles",
     "feminine-presenting, bookish, with dark Indian features"),
    ("a stage actress in a dramatic period costume with an oversized ruffled collar, a painted fan held dramatically, heeled shoes, and theatrical makeup",
     "feminine-presenting, dramatic, with Elizabethan English features"),
    ("a Patagonian gaucho in a wide-brimmed hat, a poncho draped over shoulders, bombachas trousers, high leather boots, a wide belt, and wielding a facón",
     "masculine-presenting, rugged, with Argentinian features"),
    ("a witch apprentice in a slightly-too-big pointy hat, a striped dress with apron, scuffed boots, a broom held upside down, and an anxious smile",
     "feminine-presenting, new to witchcraft, with freckled face"),
    ("a dragon-warrior princess with red scale plating on the shoulders and chest over a flowing gold-and-crimson robe, horns, a long tail, and a glaive",
     "feminine-presenting dragon character, regal and fierce"),
    ("a fantasy librarian-mage in dusty green robes, thick spectacles, a floating book beside her, ink-stained fingers, leather slippers, and a quill",
     "feminine-presenting, intellectual, with warm Middle Eastern features"),
    ("a Yoruba Egungun masquerade dancer in a costume covered entirely in colorful layered fabric strips, a face mask, and performing a spinning dance",
     "androgynous masquerade performer, vibrant and mysterious"),
    ("a Hawaiian surfer in board shorts, no shirt, shark-tooth necklace, bare feet, sandy tan, sunglasses, and carrying a surfboard under one arm",
     "masculine-presenting, chill, with Polynesian features"),
    ("a golem made of living books — body of stacked bound volumes, page-feather arms, a scroll head with handwritten face, and ribbon bookmark hair",
     "androgynous construct character, scholarly"),
    ("a Romani fortune teller in a flowing multicolored skirt, a fringed shawl, gold hoop earrings, many bracelets, bare feet, and holding a crystal ball",
     "feminine-presenting, mystical, with Roma features"),
    ("a Brazilian capoeira master in white cotton pants and a sleeveless top, bare feet, a cord belt (corda) signifying rank, and mid-flip pose",
     "masculine-presenting, acrobatic, with Afro-Brazilian features"),
    ("an 18th-century Russian Cossack in a traditional papakha fur hat, a red wool cherkeska coat with cartridge pouches, baggy trousers, boots, and a sabre",
     "masculine-presenting, hardy, with Slavic features"),
    ("a golem of sentient garbage in dented aluminum can skin, wire hair, a trash bag poncho, cereal-box hat, broken-doll eye, and mismatched shoe feet",
     "androgynous junk creature, endearing"),
    ("a Tibetan sky burial attendant in dusky maroon robes, a brass pendant, bare hands with ritual tools, and a grim but peaceful expression",
     "masculine-presenting, solemn, with Tibetan features"),
    ("a medieval jester on stilts — wearing a motley parti-colored outfit with belled hat, extreme-long stilted legs that look like wooden peg feet, and juggling",
     "androgynous, comedic, with painted face"),
    ("a celestial dragon in a mostly-human form with serpentine horns, flowing hair like clouds, silk robes with dragon embroidery, and a pearl in hand",
     "androgynous, divine, with East Asian features"),
    ("a cowgirl in a bright pink Western outfit with rhinestones, fringe, a pink cowboy hat, white boots with stars, and a rhinestone-studded lasso",
     "feminine-presenting, fabulous, with peroxide-blonde hair"),
    ("a grave robber in tattered clothing, cloth wraps on the arms, a pickaxe over the shoulder, a shovel stuck in the belt, a lantern, and a dirty face",
     "masculine-presenting, shifty, with greasy hair"),
    ("a Navajo code talker in a WWII Marine uniform, the distinctive helmet, a radio pack on the back, combat boots, a rifle slung over shoulder",
     "masculine-presenting, solemn, with Navajo features"),
    ("a renaissance portrait model in a velvet gown with gold trim, a pearl-encrusted bodice, a delicate ruff, elegant heels, and holding a small dog",
     "feminine-presenting, refined, with Italian Renaissance features"),
    ("a Thracian peltast warrior in a wide-brimmed hat, short tunic, leather sandals, a crescent pelta shield, a javelin in hand, and a short sword at hip",
     "masculine-presenting, lean, with ancient Balkan features"),
    ("a brawling tavern maid in a laced bodice, peasant blouse with rolled sleeves, a long skirt hiked up, wooden clogs, and holding a broken bottle",
     "feminine-presenting, tough, with freckled rosy cheeks"),
    ("an astronaut cat — a real cat in a tiny astronaut suit with a clear bubble helmet, tiny moon boots, a tether, and floating in a simple standing pose",
     "androgynous cat character, adventurous"),
    ("a Kabuki actor in elaborate layered silk costumes with extreme pattern, kumadori face paint, a traditional topknot wig, and holding a folding fan in a mie pose",
     "masculine-presenting, theatrical, with bold white-and-red face paint"),
    ("a sentient candle person — a tall candle body with a flaming head, wax-drip arms, a little wick-curl hair, and tiny metal holder feet",
     "androgynous object character, warm"),
    ("a steampunk detective in a Victorian-style three-piece suit modified with brass gears, a top hat with goggles, a revolver, and a wrench",
     "masculine-presenting, sharp, with mutton chops"),
    ("a Jungle tribe chief in a feather crown, a boar tusk necklace, patterned loincloth, bare feet, and holding a ceremonial ivory staff",
     "masculine-presenting, commanding, with Amazonian features"),
    ("an elite space soldier in sleek white-and-blue power armor, a full-face helmet with a blue visor, energy rifle, boots, and knee-mounted boosters",
     "gender-ambiguous due to full armor"),
    ("a Romani dancer in a long skirt of patchwork silk, coin belt, bare midriff, bangle bracelets stacked high, a head scarf with coins, and tambourine",
     "feminine-presenting, expressive, with Roma features"),
    ("a folk musician in a wool cardigan, jeans, boots, a scarf, a beanie, and playing an acoustic folk guitar with eyes closed",
     "masculine-presenting, soulful, with pale Irish features"),
    ("a medieval executioner's apprentice — younger, lankier, in a sleeveless leather tunic, a half-hood, heavy gloves, heavy boots, and carrying a bucket",
     "androgynous teen, grim"),
    ("a solar-powered desert nomad in shiny reflective robes, a sun hat with solar panels, goggles, boots, a staff with a solar orb, and a canteen",
     "androgynous, futuristic, with sun-darkened skin"),
    ("a princess in a bright pink princess dress with a poofy skirt, tiara, long elbow-length gloves, glass slippers, and carrying a single red rose",
     "feminine-presenting, classic fairy-tale, with fair features"),
    ("a Viking mead-hall skald in layered wool tunics, a fur-trimmed cloak, silver braids, leather boots, holding a drinking horn and a harp",
     "masculine-presenting, boisterous, with Nordic features"),
    ("a Korean shaman (mudang) in brightly colored ceremonial hanbok robes, a traditional black horsehair hat, leather shoes, and ringing a bell",
     "feminine-presenting, mystical, with Korean features"),
    ("a carnivorous-plant-monster girl with a big toothy pitcher-plant for a lower body she moves on, vine arms, leaf hair, and a flower-shaped face",
     "feminine-presenting plant monster, whimsically sinister"),
    ("a lovely Greek goddess Artemis in a short white chiton, leather sandals with straps, a silver moon circlet, a bow and quiver, and hunting dogs at her feet",
     "feminine-presenting, divine, with classical Greek features"),
    ("a Buddhist monk warrior in a mix of orange robes and dark monastic armor, a wooden staff, a strapped sword, sandals, and a shaved head with a scar",
     "masculine-presenting, grim, with East Asian features"),
    ("a slightly-futuristic skateboarder in neon tech-wear — LED-trimmed jacket, joggers, high-tech sneakers with lights, a visor, and a glowing skateboard",
     "androgynous, futuristic street style"),
]


@dataclass
class Prompt:
    id: str
    style: str
    character: str
    demographic: str
    pose: str
    pose_tag: str

    def full_text(self) -> str:
        finish = STYLE_FINISHES.get(self.style, "")
        return (
            f"{self.style} of {self.character}. "
            f"The character is {self.demographic}. "
            f"Posed {self.pose}. "
            f"{finish} "
            f"Single character only, centered in the frame, full body visible. "
            f"Solid plain white background. No text, no watermark, no UI elements."
        )

    def as_markdown_entry(self) -> str:
        return f"{self.id}. {self.full_text()}"


def generate_prompts(count: int, start_id: int, seed: int) -> list[Prompt]:
    rng = random.Random(seed + start_id)

    # Rotate through combinations with a global offset so each new batch
    # explores different combos instead of repeating the first batch.
    # Using (start_id - 1) as the base offset means SC-001 starts at 0,
    # SC-201 starts at 200 — so style/character/pose all rotate to new combos.
    offset = start_id - 1

    combos: list[tuple[str, str, str, str, str]] = []
    for i in range(count):
        idx = offset + i
        style = STYLES[idx % len(STYLES)]
        char, demo = CHARACTERS[(idx * 7) % len(CHARACTERS)]  # *7 to break style lockstep
        pose, pose_tag = POSES[(idx * 3) % len(POSES)]        # *3 for pose rotation
        combos.append((style, char, demo, pose, pose_tag))

    # For batches beyond the base combination space, remix character descriptions
    # with different demographic details to prevent literal duplicates
    prompts = []
    for i, (style, char, demo, pose, pose_tag) in enumerate(combos):
        pid = f"SC-{start_id + i:03d}"
        prompts.append(Prompt(
            id=pid, style=style, character=char,
            demographic=demo, pose=pose, pose_tag=pose_tag,
        ))

    return prompts


def main():
    parser = argparse.ArgumentParser(
        description="Generate diverse self-contained character prompts."
    )
    parser.add_argument("--count", type=int, default=100)
    parser.add_argument("--start_id", type=int, default=61,
                        help="First SC-### ID to use")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--output", type=Path, default=None,
                        help="Write to file; otherwise print to stdout")
    args = parser.parse_args()

    prompts = generate_prompts(args.count, args.start_id, args.seed)

    lines = []
    for p in prompts:
        lines.append(p.as_markdown_entry())
        lines.append("")

    text = "\n".join(lines)

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text)
        print(f"Wrote {len(prompts)} prompts to {args.output}")
    else:
        print(text)


if __name__ == "__main__":
    main()
